# logrotate configuration file for console logs
compress

/var/log/sophos/*/sophos-scan-*.log {
       rotate 16
       weekly
       missingok
       dateext 
       dateformat .%Y_%m_%d
       extension gz
       copytruncate
       create
}
/var/log/multiav/scan_data.log /var/log/multiav/mcafee/mcafee_report.log /var/log/mcafee/mcafee-updater.log {
       rotate 16
       weekly
       missingok
       dateext 
       dateformat .%Y_%m_%d
       extension gz
       create
}
/var/log/multiav/S3multi_scan.log /var/log/multiav/FSmulti_scan.log /var/log/multiav/scan_data.log {
       rotate 16
       weekly
       missingok
       dateext 
       dateformat .%Y_%m_%d
       extension gz
       create
}
/var/log/clamav/freshclam.log /var/log/clamav/clamav.log {
       rotate 16
       weekly
       missingok
       dateext 
       dateformat .%Y_%m_%d
       extension gz
       create
}

# packages drop log rotation information into this directory
include /etc/logrotate.d
