#!/bin/sh
### BEGIN INIT INFO
# Provides:          start,stop,restart and status of multi-scan service
# Short-Description: Enable to start,stop,restart and status of multi-scan service
# Description:       The service to virus scan objects from S3 bucket or a local directory
### END INIT INFO
#set -x
declare r MY_NAME="$(basename $0)"
declare r SCAN_HOST_NAME=${MY_NAME}
declare r ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)

declare r INPUT_SQS_PATH="https://sqs.us-east-1.amazonaws.com/$ACCOUNT_ID/<change-input-queue>"
declare r OUTPUT_SQS_PATH="https://sqs.us-east-1.amazonaws.com/$ACCOUNT_ID/<change-output-queue>"
declare r INFECTED_BUCKET="data-multiscan-infected"
declare r FS_INPUT_DIR_PATH="/var/scan/input"
declare r FS_OUTPUT_DIR_PATH="/var/scan/output"
declare r FS_INFECTED_PATH="/var/scan/infected"
declare r REGISTRY_SERVICE="registry.master.forcenex.us/gap/data-movement/multiav-scan-aws-ec2-objects/multiav-scan:latest"
declare r GB="GB"
declare r LOCAL_DEFS=false
declare r FS_SCANNERS=false
declare r DEFS_BUCKET="data-vs-definitions"
declare r DEFS_PREFIX="scanners_defs"

declare r SLACK_NOTIFY=True
declare r SLACK_CHANNEL="#alert-large-file"
#declare r SLACK_ENDPOINT=""


do_start () {
    echo "Starting S3 multi-scan service "
    # create necessary directories if they don't exist
    mkdir -p /var/scan /srv/mvs-log2/clamav /srv/mvs-log2/multiav
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Failed to create required directories "
        echo "Check permissions before proceeding"
        exit $retVal
    fi

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        declare r CPUS=`getconf _NPROCESSORS_ONLN`
        declare r MEM=`free -g | grep Mem  | awk '{print $NF}'`
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
        declare CPUS=`getconf _NPROCESSORS_ONLN`
        CPUS=$((CPUS - 1 ))
        declare r MEM=`sysctl hw.memsize | awk '{ printf "%i\n", $2/1024/1024/1024 }'`
    fi
    declare SWAPMEM=$((${MEM} + ${MEM}*3/10))
    echo "Home: ${HOME} Docker run with  CPU: ${CPUS} RAM: ${MEM} SWAP: ${SWAPMEM}"
    if [ -z ${DEFS_URI} ] 
    then 
        docker run --privileged -v ${HOME}/.aws:/root/.aws:ro  -v  /srv/mvs-log2:/var/log/:rw -v  /srv/scan:/var/scan/:rw --restart unless-stopped --cpus=${CPUS}  --memory=${MEM}${GB} --memory-swap=${SWAPMEM}${GB} -p 8009:8009 -p 2812:2812 -e FS_SCANNERS=${FS_SCANNERS} -e INPUT_SQS_PATH=${INPUT_SQS_PATH} -e OUTPUT_SQS_PATH=${OUTPUT_SQS_PATH} -e INFECTED_BUCKET=${INFECTED_BUCKET} -e FS_INPUT_DIR_PATH=${FS_INPUT_DIR_PATH} -e FS_OUTPUT_DIR_PATH=${FS_OUTPUT_DIR_PATH} -e FS_INFECTED_PATH=${FS_INFECTED_PATH} -e LOCAL_DEFS=${LOCAL_DEFS} -e DEFS_BUCKET=${DEFS_BUCKET} -e DEFS_PREFIX=${DEFS_PREFIX} -e DEFS_URI=${DEFS_URI} -e DEFS_ACCESS=${DEFS_ACCESS} -e DEFS_SECRET=${DEFS_SECRET} -e SLACK_NOTIFY=${SLACK_NOTIFY} -e SLACK_CHANNEL=${SLACK_CHANNEL} -e SLACK_ENDPOINT=${SLACK_ENDPOINT} --hostname ${SCAN_HOST_NAME} -d --name mvs ${REGISTRY_SERVICE}
    else
        docker run --privileged -v ${HOME}/.aws:/root/.aws:ro  -v  /srv/mvs-log2:/var/log/:rw -v  /srv/scan:/var/scan/:rw --restart unless-stopped --cpus=${CPUS}  --memory=${MEM}${GB} --memory-swap=${SWAPMEM}${GB} -p 8009:8009 -p 2812:2812 -e FS_SCANNERS=${FS_SCANNERS} -e INPUT_SQS_PATH=${INPUT_SQS_PATH} -e OUTPUT_SQS_PATH=${OUTPUT_SQS_PATH} -e INFECTED_BUCKET=${INFECTED_BUCKET} -e FS_INPUT_DIR_PATH=${FS_INPUT_DIR_PATH} -e FS_OUTPUT_DIR_PATH=${FS_OUTPUT_DIR_PATH} -e FS_INFECTED_PATH=${FS_INFECTED_PATH} -e LOCAL_DEFS=${LOCAL_DEFS} -e DEFS_BUCKET=${DEFS_BUCKET} -e DEFS_PREFIX=${DEFS_PREFIX} -e SLACK_NOTIFY=${SLACK_NOTIFY} -e SLACK_CHANNEL=${SLACK_CHANNEL} -e SLACK_ENDPOINT=${SLACK_ENDPOINT} --hostname ${SCAN_HOST_NAME} -d --name mvs ${REGISTRY_SERVICE}
    fi
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Error, failed to start scan service"
    fi
    exit $retVal
}
do_stop () {
    echo "Stopping scan service "
    docker stop mvs || true && docker rm mvs || true 
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Failed to stop scan service. Verify that it is still running "
    fi
    return $retVal
}
do_prune () {
    echo "Pruning docker images"
    docker system prune  -fa
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Failed to remove scan service docker image."
    fi
    return $retVal
}

Help()
{
   # Display Help
   echo "Multi Virus Scanner Service"
   echo
   echo "Syntax: $0  <star|restart> [-a|b|l|p|s|u|h]"
   echo "options:"
   echo "a     - Access Key"
   echo "s     - Secret Key"
   echo "b     - S3 Bucket with virus definitions"
   echo "p     - Prefix in S3 bucket "
   echo "l     - Download local virus definitions"
   echo "u     - URI override - used in Minio"
   echo "h     - Print this Help."
   echo
}

# echo "The number of arguments is: $#"
if [ $# -gt 1 ]
then
    command=$1
fi    
# For start/restart we need to check for additional arguments 
# if download of local virus definition files from S3 or Minio 
# is required
bucket=false
prefix=false
access_key=false
secret_key=false
url=false
case "$1" in
    start|restart)
       OPTIND=2
       while getopts "fa:hb:lp:s:u:" option; do
          case $option in
             h|help) # display Help
                Help
                exit;;
             b) # bucket
                bucket=true
                DEFS_BUCKET=${OPTARG};;
             f) # FS scanners
                FS_SCANNERS=true
                echo "FS scanners";;
             l) # local defs
                LOCAL_DEFS=true
                echo "Local defs";;
             p) # prefix
                prefix=true
                DEFS_PREFIX=${OPTARG};;
             a) # access key 
                access_key=true
                DEFS_ACCESS=${OPTARG};;
             s) # secret key 
                secret_key=true
                DEFS_SECRET=${OPTARG};;
             u) # url 
                url=true
                DEFS_URI=${OPTARG};;
            \?) # Invalid option
                echo "Error: Invalid option"
                Help
                exit;;
          esac
       done
esac

echo "LOCAL_DEFS: $LOCAL_DEFS FS_SCANNERS: $FS_SCANNERS Bucket; $DEFS_BUCKET prefix: $DEFS_PREFIX url: ${url} access key: ${access_key} secret_key: ${secret_key}"
if [ $LOCAL_DEFS = true ]
then 
if [[ ! $bucket = true ]]
then
    backet=$DEFS_BUCKET
    echo "WARNING: local download is specified bucket not provided defaulting to: $bucket"
fi
if [[ $url = true  && ( $access_key = false || $secret_key = false ) ]] 
then
    echo "1 If Minio is used then url, access key and secret key must all be provided"
    Help
    exit

elif [[ $url = false && ( $access_key = true  || $secret_key = true ) ]]
then
    echo "2 If Minio is used then url, access key and secret key must all be provided"
    Help
    exit
fi
fi
echo "command: $1 FS_SCANNERS=${FS_SCANNERS} DEFS_BUCKET=${DEFS_BUCKET} LOCAL_DEFS=${LOCAL_DEFS} DEFS_PREFIX=${DEFS_PREFIX} DEFS_ACCESS=${DEFS_ACCESS} DEFS_SECRET=${DEFS_SECRET} DEFS_URI=${DEFS_URI}"
# exit 0

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart)
        do_stop
        do_start
        ;;

    reload|force-reload)
        do_stop
        do_prune
        do_start
        ;;

    status)
        docker ps | grep -q multiav-scan
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "scan service is not running "
        else
            echo "scan service is running "
        fi
        exit $retVal
        ;;

    prune)
        do_prune
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload|status|prune}"
        exit 1
        ;;
esac
exit 0

