apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.project.name }}
  ports:
  - name: "2812"
    port: {{ .Values.service.port1 }}
    targetPort: {{ .Values.service.port1 }}
  - name: "8009"
    port: {{ .Values.service.port2 }}
    targetPort: {{ .Values.service.port2 }}
  - name: "2820"
    port: {{ .Values.service.port3 }}
    targetPort: {{ .Values.service.port3 }}
